version: "3.0"

services:
    web:
        container_name: web     
        image: web:1
        platform: linux/amd64
        hostname: web
        stdin_open: true
        tty: true
        privileged: true
        ports:
            - "80:80"
            - "9080:8080"
            - "9922:22"
            - "9990:9990"
            - "9736:9736"
            - "8088:8088"
        networks:
            web_network:
                ipv4_address: 192.168.1.3
                
networks:
  web_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24